language: node_js
node_js: stable
branches:
  only:
  - develop
before_install:
- npm install -g hexo
- npm install -g hexo-cli
- "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
install:
- npm install
script:
- git clone -b master https://github.com/wangming1993/wangming1993.github.com.git public
- hexo generate
after_success:
  - cd ./public
  #- git init
  - git config --global user.name 'wangming1993'
  - git config --global user.email 'wangming19932008@163.com'
  - git add .
  - git commit -m ${TRAVIS_COMMIT_MSG}
  - git push --force "https://wangming1993:${REPO_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/wangming1993/wangming1993.github.com.git
